export interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  isMaharajasPick?: boolean;
  aiHint?: string;
  category: string;
  categoryDisplayName: string;
  description: string;
  material: string;
  sizes: string[];
  rating: number;
  reviewCount: number;
}

export const products: Product[] = [
  // Royal Attire
  {
    id: 2,
    name: 'Royal Peshwa Turban (Safas)',
    price: 4999,
    image: '/product-pictures/tubun.jpg',
    isMaharajasPick: false,
    aiHint: 'royal turban',
    category: 'royal-attire',
    categoryDisplayName: 'Royal Attire',
    description: 'A majestic Peshwa-style turban, hand-wrapped with the finest silk and adorned with a traditional brooch. Perfect for weddings and royal ceremonies.',
    material: 'Silk',
    sizes: ['Small', 'Medium', 'Large'],
    rating: 4.8,
    reviewCount: 32,
  },
  {
    id: 5,
    name: 'Traditional Paithani Saree',
    price: 12500,
    image: '/product-pictures/pathani saare.jpg',
    isMaharajasPick: true,
    aiHint: 'silk saree',
    category: 'royal-attire',
    categoryDisplayName: 'Royal Attire',
    description: 'An authentic hand-woven Paithani saree, featuring intricate peacock motifs and a rich, shimmering texture. A timeless piece of Maharashtrian heritage.',
    material: 'Silk',
    sizes: ['One Size'],
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: 9,
    name: "Maharani's Pearl Necklace",
    price: 25000,
    image: '/product-pictures/necklace.jpg',
    aiHint: 'pearl necklace',
    category: 'royal-attire',
    categoryDisplayName: 'Royal Attire',
    description: 'An elegant pearl necklace inspired by the jewelry of Maratha queens. Each pearl is hand-selected for its luster and quality.',
    material: 'Pearl',
    sizes: [],
    rating: 5.0,
    reviewCount: 18,
  },
  {
    id: 10,
    name: 'Embroidered Velvet Mojaris',
    price: 3200,
    image: '/product-pictures/mojaris.jpg',
    aiHint: 'velvet shoes',
    category: 'royal-attire',
    categoryDisplayName: 'Royal Attire',
    description: 'Step into royalty with these handcrafted velvet mojaris, featuring intricate gold thread embroidery. Comfortable and stylish for any grand occasion.',
    material: 'Velvet',
    sizes: ['7', '8', '9', '10'],
    rating: 4.6,
    reviewCount: 25,
  },
  {
    id: 16,
    name: 'Sardar Angarkha (Kurta)',
    price: 7800,
    image: "/product-pictures/angrakha kurta '.jpg",
    aiHint: 'royal kurta',
    category: 'royal-attire',
    categoryDisplayName: 'Royal Attire',
    description: 'A traditional Angarkha-style kurta for men, crafted from fine cotton silk. Its overlapping design is a symbol of Maratha warrior attire.',
    material: 'Cotton Silk',
    sizes: ['S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviewCount: 29,
  },
  {
    id: 17,
    name: 'Kolhapuri Saaj Necklace',
    price: 18500,
    image: '/product-pictures/kholapuri saaj nechlace.jpg',
    aiHint: 'traditional necklace',
    category: 'royal-attire',
    categoryDisplayName: 'Royal Attire',
    description: 'A traditional Kolhapuri Saaj necklace, symbolizing marital bliss and prosperity. An iconic piece of Maharashtrian jewelry.',
    material: 'Gold Plated',
    sizes: [],
    rating: 4.9,
    reviewCount: 38,
  },

  // Wooden Weapons
  {
    id: 1,
    name: 'Limited Edition Dandpatta Sword',
    price: 15999,
    image: '/product-pictures/sword.jpg',
    isMaharajasPick: true,
    aiHint: 'ornate sword',
    category: 'wooden-weapons',
    categoryDisplayName: 'Wooden Weapons',
    description: 'A decorative replica of the legendary Maratha Dandpatta (Gauntlet-Sword). Hand-carved from Sheesham wood with intricate details, this is a collector\'s item.',
    material: 'Wood',
    sizes: [],
    rating: 4.9,
    reviewCount: 55,
  },
  {
    id: 3,
    name: 'Handcrafted Dhal Shield',
    price: 8499,
    image: '/product-pictures/dhal shield.jpg',
    isMaharajasPick: false,
    aiHint: 'ornate shield',
    category: 'wooden-weapons',
    categoryDisplayName: 'Wooden Weapons',
    description: 'A wooden Dhal (shield) featuring traditional Maratha art. Hand-painted by skilled artisans, it serves as a stunning piece of wall decor.',
    material: 'Wood',
    sizes: ['18-inch', '24-inch'],
    rating: 4.7,
    reviewCount: 41,
  },
  {
    id: 11,
    name: 'Decorative Bhala (Spear)',
    price: 7500,
    image: '/product-pictures/bhala.jpg',
    aiHint: 'ornate spear',
    category: 'wooden-weapons',
    categoryDisplayName: 'Wooden Weapons',
    description: 'A beautifully crafted wooden replica of a Maratha Bhala (spear). Ideal for home decor or as part of a traditional collection.',
    material: 'Wood',
    sizes: [],
    rating: 4.6,
    reviewCount: 22,
  },
  {
    id: 18,
    name: 'Maratha Khanda Sword Replica',
    price: 13500,
    image: '/product-pictures/sword.jpg',
    aiHint: 'ancient sword',
    category: 'wooden-weapons',
    categoryDisplayName: 'Wooden Weapons',
    description: 'A wooden replica of the Khanda, a double-edged straight sword. This piece showcases the martial heritage of the Marathas.',
    material: 'Wood',
    sizes: [],
    rating: 4.8,
    reviewCount: 34,
  },

  // Handicrafts
  {
    id: 4,
    name: 'Chhatrapati Shivaji Maharaj Canvas Painting',
    price: 3799,
    image: '/product-pictures/canvas paintaing.jpg',
    isMaharajasPick: true,
    aiHint: 'maratha painting',
    category: 'handicrafts',
    categoryDisplayName: 'Handicrafts',
    description: 'A vibrant canvas painting depicting Chhatrapati Shivaji Maharaj in his royal court. A masterpiece for any history enthusiast.',
    material: 'Canvas',
    sizes: ['12x18 inch', '24x36 inch'],
    rating: 4.9,
    reviewCount: 78,
  },
  {
    id: 6,
    name: 'Bronze Statue of Chhatrapati Shivaji',
    price: 9999,
    image: '/product-pictures/statue.jpg',
    isMaharajasPick: false,
    aiHint: 'bronze statue',
    category: 'handicrafts',
    categoryDisplayName: 'Handicrafts',
    description: 'A stunning bronze-finished statue of Chhatrapati Shivaji Maharaj on his throne. The intricate details capture his commanding presence.',
    material: 'Resin',
    sizes: ['8-inch', '12-inch'],
    rating: 4.8,
    reviewCount: 61,
  },
  {
    id: 7,
    name: 'Set of 6 Copper Mugs',
    price: 2999,
    image: '/product-pictures/copper mug.jpg',
    isMaharajasPick: false,
    aiHint: 'copper mugs',
    category: 'handicrafts',
    categoryDisplayName: 'Handicrafts',
    description: 'A set of six handcrafted copper mugs, embossed with Maratha emblems. Perfect for serving traditional drinks.',
    material: 'Copper',
    sizes: [],
    rating: 4.7,
    reviewCount: 92,
  },
  {
    id: 12,
    name: 'Bidri Ware Flower Vase',
    price: 4500,
    image: '/product-pictures/bidri ware flower vase.jpg',
    aiHint: 'metal vase',
    category: 'handicrafts',
    categoryDisplayName: 'Handicrafts',
    description: 'A traditional Bidri ware vase, featuring pure silver inlay on a blackened alloy. This art form was patronized by the Marathas.',
    material: 'Bidriware',
    sizes: ['6-inch', '9-inch'],
    rating: 4.8,
    reviewCount: 15,
  },
  {
    id: 19,
    name: 'Fort Raigad Wooden Carving',
    price: 8999,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'wood carving fort',
    category: 'handicrafts',
    categoryDisplayName: 'Handicrafts',
    description: 'An intricate 3D wooden carving of Fort Raigad, the capital of the Maratha Empire. A tribute to the architectural prowess of the era.',
    material: 'Wood',
    sizes: [],
    rating: 4.9,
    reviewCount: 28,
  },


  // Historical Books
  {
    id: 8,
    name: 'The Life of Chhatrapati Shivaji Maharaj Book',
    price: 999,
    image: '/book-images/the_life_of_shivaji_maharaj.png',
    isMaharajasPick: true,
    aiHint: 'old book',
    category: 'historical-books',
    categoryDisplayName: 'Historical Books',
    description: 'A comprehensive biography of Chhatrapati Shivaji Maharaj, detailing his life, strategies, and administration. Hardcover edition.',
    material: 'Paper',
    sizes: [],
    rating: 5.0,
    reviewCount: 152,
  },
  {
    id: 13,
    name: 'History of the Marathas',
    price: 1499,
    image: '/book-images/the_maratha_centure.png',
    aiHint: 'history book',
    category: 'historical-books',
    categoryDisplayName: 'Historical Books',
    description: 'A detailed account of the Maratha Empire, from its rise to its peak. A must-read for history buffs.',
    material: 'Paper',
    sizes: [],
    rating: 4.9,
    reviewCount: 89,
  },
  {
    id: 20,
    name: 'Biography of Chhatrapati Sambhaji Maharaj',
    price: 1199,
    image: '/book-images/the_life_and_death_of_shambaji_maharaj.png',
    aiHint: 'biography book',
    category: 'historical-books',
    categoryDisplayName: 'Historical Books',
    description: 'Explore the life of the valiant Chhatrapati Sambhaji Maharaj, the son of Chhatrapati Shivaji Maharaj, through this engaging biography.',
    material: 'Paper',
    sizes: [],
    rating: 4.8,
    reviewCount: 75,
  },

  // Souvenirs
  {
    id: 14,
    name: 'Raigad Fort Miniature Model',
    price: 2199,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'fort model',
    category: 'souvenirs',
    categoryDisplayName: 'Souvenirs',
    description: 'A detailed miniature model of the historic Raigad Fort. A perfect souvenir to remember the glory of the Maratha capital.',
    material: 'Resin',
    sizes: [],
    rating: 4.7,
    reviewCount: 112,
  },
  {
    id: 15,
    name: 'Chhatrapati Shivaji Maharaj Commemorative Coin',
    price: 899,
    image: '/product-pictures/coin.jpg',
    aiHint: 'gold coin',
    category: 'souvenirs',
    categoryDisplayName: 'Souvenirs',
    description: 'A beautifully minted commemorative coin featuring the bust of Chhatrapati Shivaji Maharaj on one side and the "Rajmudra" on the other.',
    material: 'Brass',
    sizes: [],
    rating: 4.9,
    reviewCount: 210,
  },
  {
    id: 21,
    name: 'Maratha Empire Map Print',
    price: 1599,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'old map',
    category: 'souvenirs',
    categoryDisplayName: 'Souvenirs',
    description: 'A high-quality print of a historical map showing the expanse of the Maratha Empire at its peak. Framed and ready to hang.',
    material: 'Archival Paper',
    sizes: ['A3', 'A2'],
    rating: 4.8,
    reviewCount: 95,
  },
];
